### PR TITLE
Feature/bayesboot2

### PR DESCRIPTION
**Pull request by mammykins**

### CODE REVIEW

**Comment by ellieking17** [comment]
In the notebook for reading data I needed to change the filepath to:
`filepath = os.path.join(
    DATA_DIR, "sampled_journey",
    filename)`
to read in the file created in the previous step. I think that's going to be standard but i was in the master branch when I created the data so i might be wrong

**Comment by ellieking17** [comment]
There's no Makefile so i needed to use `pip install -r requirements.txt`

**Comment by mammykins** [comment]
The reading data was changed to 
`filepath = os.path.join( DATA_DIR, "sampled_journey", filename)` in the notebook

**Comment by mammykins** [comment]
Corrected README package dependency instructions. Added suggestion of makefile as an issue to automate the pipeline and clarify the sequence of scripts.

**Pull request merged**
